  version: '3.8'

  services:
    app:
      build:
        context: .
        dockerfile: Dockerfile
      container_name: laravel_app
      volumes:
        - ./:/var/www/html
      networks:
        - app-network
      environment:
        - APP_ENV=local
        - APP_DEBUG=true
        - DB_CONNECTION=pgsql
        - DB_HOST=db
        - DB_PORT=5432
        - DB_DATABASE=${DB_DATABASE}
        - DB_USERNAME=${DB_USERNAME}
        - DB_PASSWORD=${DB_PASSWORD}

    webserver:
      image: nginx:alpine
      container_name: nginx_webserver
      restart: unless-stopped
      ports:
        - "80:80"
      volumes:
        - ./:/var/www/html
        - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      depends_on:
        - app
      networks:
        - app-network

    db:
      image: postgres:13
      container_name: postgres_db
      restart: unless-stopped
      environment:
        POSTGRES_DB: ${DB_DATABASE}
        POSTGRES_USER: ${DB_USERNAME}
        POSTGRES_PASSWORD: ${DB_PASSWORD}
      # ports:
      #   - "5433:5432"
      volumes:
        - pgdata:/var/lib/postgresql/data
      networks:
        - app-network

  volumes:
    pgdata:

  networks:
    app-network:
      driver: bridge
