version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    networks:
      - app-network
    environment:
      - APP_NAME=Laravel
      - APP_ENV=local
      - APP_KEY=base64:+FEr5+Ql3DYdcBqF4KbOGyVzU/lDsvNLaH5749QUHaE=
      - APP_DEBUG=true
      - APP_URL=http://localhost
      
      - LOG_CHANNEL=stack
      - LOG_DEPRECATIONS_CHANNEL=null
      - LOG_LEVEL=debug
      
      - DB_CONNECTION=pgsql
      - DB_HOST=172.31.0.2
      - DB_PORT=5432
      - DB_DATABASE=thelastecole
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      
      - FIREBASE_CREDENTIALS=/var/www/html/gestion-pedagogique-laravel.json
      - FIREBASE_DATABASE_URL=https://gestion-pedagogique-laravel-default-rtdb.firebaseio.com/
      - FIREBASE_API_KEY=AIzaSyBgXAEvu7TJAlCJXL8oOGX-e55wAyJNlg4
      - FIREBASE_STORAGE_BUCKET=gs://gestion-pedagogique-laravel.appspot.com
      
      - BROADCAST_DRIVER=log
      - CACHE_DRIVER=file
      - FILESYSTEM_DISK=local
      - QUEUE_CONNECTION=sync
      - SESSION_DRIVER=file
      - SESSION_LIFETIME=120
      
      - MEMCACHED_HOST=127.0.0.1
      
      - REDIS_HOST=127.0.0.1
      - REDIS_PASSWORD=null
      - REDIS_PORT=6379
      
      - MAIL_MAILER=smtp
      - MAIL_HOST=mailpit
      - MAIL_PORT=1025
      - MAIL_USERNAME=null
      - MAIL_PASSWORD=null
      - MAIL_ENCRYPTION=null
      - MAIL_FROM_ADDRESS="hello@example.com"
      - MAIL_FROM_NAME="${APP_NAME}"
      
      - AWS_ACCESS_KEY_ID=
      - AWS_SECRET_ACCESS_KEY=
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_BUCKET=
      - AWS_USE_PATH_STYLE_ENDPOINT=false
      
      - PUSHER_APP_ID=
      - PUSHER_APP_KEY=
      - PUSHER_APP_SECRET=
      - PUSHER_HOST=
      - PUSHER_PORT=443
      - PUSHER_SCHEME=https
      - PUSHER_APP_CLUSTER=mt1
      
      - VITE_PUSHER_APP_KEY="${PUSHER_APP_KEY}"
      - VITE_PUSHER_HOST="${PUSHER_HOST}"
      - VITE_PUSHER_PORT="${PUSHER_PORT}"
      - VITE_PUSHER_SCHEME="${PUSHER_SCHEME}"
      - VITE_PUSHER_APP_CLUSTER="${PUSHER_APP_CLUSTER}"
      
      - AUTH_DRIVER=passport #passport ou firebase

  webserver:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
    networks:
      - app-network

  pgsql:
    image: postgres:14
    container_name: gestion-pdagogique-laravel-last-pgsql-1
    environment:
      POSTGRES_DB: thelastecole
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    
    ports:
      - "5432:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
